name: Deploy to Cocoapods

on:
  release:
    types:
      - published
      
jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        ref: 'master'
    
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' 
        
    - name: Install dependencies
      run: |
        gem install cocoapods
        git submodule sync --recursive && git submodule update --recursive --init
    
    - name: Push to cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
